export const CREATE_WHITEBOARD_ITEM_PENDING = 'whiteboarding/CREATE_WHITEBOARD_ITEM_PENDING';
export const CREATE_WHITEBOARD_ITEM_COMPLETE = 'whiteboarding/CREATE_WHITEBOARD_ITEM_COMPLETE';

export const DELETE_WHITEBOARD_ITEM_COMPLETE = 'whiteboarding/DELETE_WHITEBOARD_ITEM_COMPLETE';


export const UPVOTE_WHITEBOARD_ITEM_COMPLETE = 'whiteboarding/UPVOTE_WHITEBOARD_ITEM_COMPLETE';
export const DOWNVOTE_WHITEBOARD_ITEM_COMPLETE = 'whiteboarding/DOWNVOTE_WHITEBOARD_ITEM_COMPLETE';

export const DEVOTE_WHITEBOARD_ITEM_COMPLETE = 'whiteboarding/DEVOTE_WHITEBOARD_ITEM_COMPLETE';
